// enable store for auth module

export const getters = {
    getCities: () => {
        let cities = [
            "Paris",
            "Lyon",
            "Marseille",
            "Toulouse",
            "Nice",
            "Nantes",
            "Strasbourg",
            "Montpellier",
            "Bordeaux",
            "Lille",
            "Rennes",
            "Reims",
            "Le Havre",
            "Saint-Étienne",
            "Toulon",
            "Grenoble",
            "Dijon",
            "Angers",
            "Villeurbanne",
            "Brest",
            "Le Mans",
            "Clermont-Ferrand",
            "Amiens",
            "Aix-en-Provence",
            "Limoges",
            "Tours",
            "Nîmes",
            "Perpignan",
            "Besançon",
            "Orléans",
            "Mulhouse",
            "Metz",
            "Rouen",
            "Caen",
            "Nancy",
            "Saint-Denis",
            "Aulnay-sous-Bois",
            "Argenteuil",
            "Montreuil",
            "Versailles",
            "Roubaix",
            "Asnieres-sur-Seine",
            "Aubervilliers",
            "Cergy",
            "Colombes",
            "Pau",
            "Mérignac",
            "Saint-Maur-des-Fossés",
            "Saint-Nazaire",
            "Saint-Quentin",
            "Saint-Priest",
            "Saint-Malo",
        ]
        return cities.sort()
    },
}
